[package]
name = "npm-updater"
version = "0.1.0"
authors = ["Karol Kozakowski <cosaquee@gmail.pl>"]

[dependencies]
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"
pretty_env_logger = "0.2.2"
serde_json = "1.0"
serde_derive = "1.0.27"
serde = "1.0.27"
reqwest = "0.8.5"
semver = "0.9.0"